#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InA { int a[]; };
layout(set = 0, binding = 1) buffer InB { int b[]; };
layout(set = 0, binding = 2) buffer OutC { int c[]; };
layout(set = 0, binding = 3) buffer N { int n[]; };


void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < uint(n[0])) {
        c[idx] = a[idx] + b[idx];
    }
}